### ISSUE TITLE
`eris init` leaves ~/eris/services empty; no service definitions

### ISSUE THREAD

**Issue by AronVanAmmers** [eris-ltd/eris-cli#138]
I followed the install steps on a fresh Ubuntu 14.04. After `eris init`, the directory `~/.eris/services` remained empty, hence no known services. Output of `eris services known` was empty.

A workaround is getting the contents of https://github.com/eris-ltd/eris-services and placing it in `~/.eris/services`.

**Comment by compleatang** [comment]
fixed by af8f135

**Comment by nikolai-b** [comment]
I'm still getting this
```bash
$ go version && echo $GOPATH
> go version go1.4.2 linux/amd64
> /home/user/.gvm/pkgsets/go1.4.2/global
$ cd $GOPATH/src/github.com/eris-ltd/eris-cli/cmd/eris
$ git rev-parse HEAD
> a371286d...
$ go install
$ cd ~
$ rm -rf .eris
$ eris init
$ ls .eris/services
```
Might be slightly different as when I copied https://github.com/eris-ltd/eris-services into `~/.eris/services` and `eris services known` was still blank.

**Comment by zramsay** [comment]
a fix for this is a pending PR. init has been refactored. I'll ping you when it's merged.
