### ISSUE TITLE
Windows: does not connect to docker

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#323]
I followed the instructions from https://docs.erisindustries.com/tutorials/getting-started/ but Docker seems to be having some issues:

    C:\Users\sbuergel>docker version
    Client:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   76d6bc9
     Built:        Tue Nov  3 19:20:09 UTC 2015
     OS/Arch:      windows/amd64
    An error occurred trying to connect: Get http://localhost:2375/v1.21/version: di
    al tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the ta
    rget machine actively refused it.

I also tried deleting my machine and creating a new one with the Docker Quickstart Terminal (note, this point is not written in the getting started guide so this might have been a mistake(?)). I think this is the reason for then eris having issues with its init:

    C:\Users\sbuergel>eris init -d
    Connecting to the Docker Client via =>  :
    Checking Details via Docker-Machine =>  eris
    Querying the eris docker-machine's url.
    Could not connect to the eris docker-machine.
    Error:  Could not evaluate the env vars for the eris docker-machine.
    Error:  exit status 1
    Trying "default" docker-machine.
    Querying the default docker-machine's url.
            URL =>                  tcp://192.168.99.100:2376
    Querying the default docker-machine's certificate path.
            Certificate Path =>     .
    Querying whether the host and user have access to the right files for TLS connec
    tion to docker.
    Could not connect to the "default" docker-machine.
    Error:  The marmots could not find a file that was required to connect to Docker
    .
    They get a file does not exist error from the OS.
    File needed:    cert.pem
    Trying to set up a new machine.

This is weird because the Docker machine says:

    docker is configured to use the default machine with IP 192.168.99.100
    For help getting started, check out the docs at https://docs.docker.com
Any help would be appreciated!

**Comment by androlo** [comment]
Not on the cli team but I can almost guarantee this is a cli issue which will require a patch.

**Comment by zramsay** [comment]
Hi @SCBuergel, this is a known issue that's nearing the top of our stack. Somewhat related to #280 and other similar issues on docker sequencing for non-Linux.  We're still recommending running eris on Ubuntu although this series of commands should work:

`docker-machine create --driver virtualbox eris`
`docker-machine env eris`
`eval "$(docker-machine env eris)"`

This'll solve `Error:  Could not evaluate the env vars for the eris docker-machine.` and the first command should create `cert.pem`. see [here](https://docs.docker.com/machine/get-started/) for more info.

**Comment by SCBuergel** [comment]
Hi @zramsay, thanks for your feedback. I am running your suggested commands in cmd (windows), the first two work fine, the I get 

    C:\Users\sbuergel>eval "$(docker-machine env eris)"
    'eval' is not recognized as an internal or external command,
    operable program or batch file.

Also copy pasting the output does not work:

    C:\Users\sbuergel>export DOCKER_TLS_VERIFY="1"
    'export' is not recognized as an internal or external command,
    operable program or batch file.

Given the pain to get docker to run on Windows, I do not see much of a reason to rely on Docker in the first place. Maybe in the long-run consider going for a native Windows version.

**Comment by compleatang** [comment]
@SCBuergel, erisdb should build fine in windows 32 bit but has challenges in 64 bit. We have very few Windows users, so thanks for filing the bug report. 

This is fixed in the most latest version (although you'll have to use docker's shell rather than cmd from the start menu). Am going to close this for now.

**Comment by cataquil** [comment]
its a bug with the docker for windows install.  if you run from windows command line, even after adding c:/Program Files/git/cmd to your path you still cannot call the 'EVAL' command.  Try running it in the MING64 Bash command line that git for windows installs.  It gives you a few more unix cli commands. I had this bug when creating a nodejs microservice on windows and this page came up in google. but looks like a cool project.

**Comment by alixandru** [comment]
@cataquil you need to run `docker` commands from within Git Bash shell. Windows' `cmd` won't work at the moment.

**Comment by pietv** [comment]
@alixandru a small `.bat` script with these contents 
```
@echo off
for /f "tokens=*" %%i in ('docker-machine env --shell=cmd eris') do %%i
```
should work (Docker Machine version 0.5 and above) — no need for Bash.

**Comment by alixandru** [comment]
@pietv The problem is with `docker-machine` itself. It gives an error, no matter what command I run (`env`, `ls`, `config`, etc), so it can't even get to run the script you mentioned.

Perhaps there's something wrong with my setup, or indeed there's a bug within `docker-machine`. I have Windows 10 and I already had Git installed when I installed the Docker Toolbox (maybe that's the cause). 

Anyway, I could get it working by manually getting into bash and working from there, so it's not a show stopper. Thanks, anyway!

**Comment by compleatang** [comment]
Weird. Assuming you have it in your path and are running from Docker QuickStart Terminal, do you remember what the error was for others who may come across this issue in the future?

**Comment by alixandru** [comment]
From Docker QuickStart Terminal it gets me to Git Bash directly and there's no error.
I can't remember if there was any configuration option during Docker Toolbox setup to use Git Bash.

**Comment by compleatang** [comment]
Thanks!

**Comment by pietv** [comment]
Thank you for the info indeed!

I wonder what the error `docker-machine` gives you when you issue the `docker-machine ls` command. It should only list available/bad machines? Thanks.

**Comment by alixandru** [comment]
Here's my output from Windows CMD:

```
>docker-machine ls
NAME     ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
docker   *        virtualbox   Running                 Unknown   Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 1
output  : 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

From Git Bash, no error whatsoever:

```
MINGW64 ~
$ docker-machine ls
NAME     ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
docker   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.10.3
```

**Comment by alixandru** [comment]
I do need to mention that I also have Gow installed which adds a `ssh` command to my path, and that `ssh` command is an alias to:

"C:\Program Files (x86)\Gow\bin\ssh.bat"
```
@echo off
plink %1 %2 %3 %4 %5 %6 %7 %8 %9
```

**Comment by pietv** [comment]
oh wow. yes, this looks really peculiar, and this is definitely an issue with the `docker-machine`. I think you should create an issue about it if its their latest version (0.6.0) github.com/docker/machine/issues

> "C:\Program Files (x86)\Gow\bin\ssh.bat"
i don't really know if this is related. docker-machine communicates via `ssh` with the machines internally. it doesn't (shouldn't) invoke your environment's `ssh.exe`/`ssh.bat` command.

Unless you haven't done this already, could you please recreate your `docker` machine from within `cmd.exe`?

```
C:\> docker-machine rm docker
C:\> docker-machine create -d virtualbox docker
```

**Comment by alixandru** [comment]
I did try recreating it from cmd and it's not working. Gets stuck
somewhere, don't remember where. I'll open an issue with them. Thanks.

**Comment by pietv** [comment]
sorry, @alixandru. this is really strange that you can't even recreate the machine. please kindly update us (Eris team) on the issue, we're really curious too. Thanks very much!

**Comment by alixandru** [comment]
Looks like there there are already a couple of issues opened in Docker Machine project related to this. 
https://github.com/docker/machine/issues/3152
https://github.com/docker/machine/issues/3007
I updated both of them with my findings. Thanks for your support, guys!

**Comment by pietv** [comment]
@alixandru, thank you for your discovery and help! Indeed from those two issues it looks like having an alternative `ssh` might cause problems. Anxious to know how this evolves on the DM side! Thanks!
